import Foundation

struct ExampleScore: Identifiable, Hashable {
    let id: String
    let title: String
    let subtitle: String
    let source: String

    static let all: [ExampleScore] = [
        ExampleScore(
            id: "simple-scale",
            title: "C 大调练习",
            subtitle: "v0.2 离线编译 MVP 示例",
            source: """
            \\version "2.24.0"
            \\language "english"

            \\header {
              title = "C Major Practice"
              composer = "LilyPad"
              tagline = ##f
            }

            \\score {
              \\relative c' {
                \\key c \\major
                \\time 4/4
                c4 d e f | g2 g |
                a4 g f e | d2 c \\bar "|."
              }
              \\layout { }
              \\midi { }
            }
            """
        ),
        ExampleScore(
            id: "ipad-landscape",
            title: "iPad 横屏模板",
            subtitle: "A4 landscape + 简单旋律",
            source: """
            \\version "2.24.0"
            \\language "english"

            \\paper {
              #(set-paper-size "a4landscape")
            }

            \\header {
              title = "iPad Landscape Demo"
              subtitle = "Offline preview generated by LilyPad"
              tagline = ##f
            }

            \\score {
              \\relative c' {
                \\key g \\major
                \\time 3/4
                g4 a b | c2 b4 | a4 g fis | g2. \\bar "|."
              }
              \\layout { }
            }
            """
        )
    ]
}
