\version "2.24.0"
\language "english"

\paper {
  #(set-paper-size "a4landscape")
}

\header {
  title = "iPad Landscape Demo"
  subtitle = "Offline preview generated by LilyPad"
  tagline = ##f
}

\score {
  \relative c' {
    \key g \major
    \time 3/4
    g4 a b | c2 b4 | a4 g fis | g2. \bar "|."
  }
  \layout { }
}
